### ISSUE TITLE
docker hub

### ISSUE THREAD

**Issue by mabed-fr** [Tomy2e/livebox-exporter#1]
Hello,

Are there plans to publish the image to docker hub?

Mabed

**Comment by Tomy2e** [comment]
Hi @mabed-fr,

I don't know if you noticed but a Docker image is already available on [Github container registry](https://github.com/Tomy2e/livebox-exporter/pkgs/container/livebox-exporter):

```bash
$ docker pull ghcr.io/tomy2e/livebox-exporter:latest
```

For this reason, I'm not planning to publish it to Docker Hub.

I'm closing this issue, but feel free to reopen it if you think there is a specific need to have it on Docker Hub as well.
