### ISSUE TITLE
Datas a exposer ?

### ISSUE THREAD

**Issue by ManuDuSud** [Tomy2e/livebox-exporter#12]
Hello j'ai testé les 2 exporters pour Livebox qui existent.

 Le tiens fonctionne mieux car les valeurs des  bandes passantes sont bonnes. (bench avec 2 serveurs à travers la livebox)

Toutefois sur l'exporter : https://github.com/eric-b/livebox-exporter
Il y a des données interessantes : "Température de l'ONT" ainsi que les "ONT throughput " que tu n'exportes pas.
C'est possible de le rajouter dans ton exporter?

Voici mon dashboard en test:

![image](https://github.com/user-attachments/assets/ec3dd880-5a22-410c-a5d6-2f60b5b4ce07)

**Comment by Tomy2e** [comment]
Oui c'est pas mal d'avoir la température. C'est implémenté dans #16. Je vais tester quelques jours pour vérifier que c'est stable avant de merger.
J'ai poussé une image Docker de test ici: `ghcr.io/tomy2e/livebox-exporter:dev-ont`

Ça donne ça côté Grafana:
![image](https://github.com/user-attachments/assets/a7571bee-077a-4d33-9880-8fef1fdb83d1)

**Comment by Tomy2e** [comment]
Les nouvelles metrics sont dispo en [v0.5.0](https://github.com/Tomy2e/livebox-exporter/releases/tag/v0.5.0)
