### ISSUE TITLE
Erreur 196618 avec l'option -experimental sur une Livebox 7

### ISSUE THREAD

**Issue by ManuDuSud** [Tomy2e/livebox-exporter#15]
Pour info :

livebox-exporter-2    | 2024/08/09 10:05:36 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: HomeLan.Interface.vap5g0priv1.Stats
livebox-exporter-2    | 2024/08/09 10:05:41 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: HomeLan.Interface.vap5g0priv1.Stats
livebox-exporter-2    | 2024/08/09 10:05:46 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: HomeLan.Interface.vap5g0priv1.Stats
livebox-exporter-2    | 2024/08/09 10:05:51 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: HomeLan.Interface.vap5g0priv1.Stats

**Comment by Tomy2e** [comment]
Je pense que je vois où est le problème. Peux-tu installer l'outil [livebox-cli](https://github.com/Tomy2e/livebox-api-client?tab=readme-ov-file#livebox-cli-usage) que je viens de mettre en ligne et me donner le résultat de cette commande stp ? (ne pas oublier de définir la variable d'environnement `ADMIN_PASSWORD`)

```console
$ livebox-cli -service HomeLan.Interface -method get
```

Actuellement la découverte des interfaces se fait de cette façon:

```console
$ livebox-cli -service NeMo.Intf.data -method getMIBs -params '{"traverse":"all", "flag": "statmon && !vlan"}' | jq .status.base
```

J'aimerais voir s'il y a une différence entre les interfaces retournées par `NeMo.Intf.data` et celles retournées par `HomeLan.Interface`. Notamment si l'interface `vap5g0priv1` est bien présente dans le résultat de la première commande.

Merci d'avance !

**Comment by ManuDuSud** [comment]
root@51719e1fe980:/go# ./livebox-cli -service HomeLan.Interface -method get
`
{"status":{"vap2g0priv0":{"FriendlyName":"2.4GHz-Private_SSID","Name":"vap2g0priv0","Alias":"WiFi","NumberOfStoredMeasures":5860},"vap5g0priv0":{"FriendlyName":"5GHz-Private_SSID","Name":"vap5g0priv0","Alias":"WiFi","NumberOfStoredMeasures":5858},"vap6g0priv0":{"FriendlyName":"6GHz-Private_SSID","Name":"vap6g0priv0","Alias":"WiFi","NumberOfStoredMeasures":5746},"ETH0":{"FriendlyName":"LAN-10G","Name":"ETH0","Alias":"Eth","NumberOfStoredMeasures":5786},"ETH1":{"FriendlyName":"eth1","Name":"ETH1","Alias":"Eth","NumberOfStoredMeasures":5426},"ETH2":{"FriendlyName":"eth2","Name":"ETH2","Alias":"Eth","NumberOfStoredMeasures":5352},"ETH3":{"FriendlyName":"eth3","Name":"ETH3","Alias":"Eth","NumberOfStoredMeasures":507},"eth1_wan":{"FriendlyName":"WAN_Ethernet","Name":"ETH1","Alias":"WAN_Virtual","NumberOfStoredMeasures":5426},"ETH4":{"FriendlyName":"eth4","Name":"ETH4","Alias":"Eth","NumberOfStoredMeasures":508},"vlan_data":{"FriendlyName":"WAN_Ethernet-Internet","Name":"vlan_data","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"vlan_multi":{"FriendlyName":"WAN_Ethernet-MultiServices","Name":"vlan_multi","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"vlan_voip":{"FriendlyName":"WAN_Ethernet-VoIP","Name":"vlan_voip","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"vlan_iptv1":{"FriendlyName":"WAN_Ethernet-IPTV_VOD","Name":"vlan_iptv1","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"vlan_iptv2":{"FriendlyName":"WAN_Ethernet-IPTV_Live","Name":"vlan_iptv2","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"veip0":{"FriendlyName":"WAN_GPON","Name":"veip0","Alias":"WAN_Virtual","NumberOfStoredMeasures":5861},"gvlan_data":{"FriendlyName":"WAN_GPON-Internet","Name":"gvlan_data","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"gvlan_multi":{"FriendlyName":"WAN_GPON-MultiServices","Name":"gvlan_multi","Alias":"WAN_Virtual","NumberOfStoredMeasures":5857},"gvlan_voip":{"FriendlyName":"WAN_GPON-VoIP","Name":"gvlan_voip","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"gvlan_iptv1":{"FriendlyName":"WAN_GPON-IPTV_VOD","Name":"gvlan_iptv1","Alias":"WAN_Virtual","NumberOfStoredMeasures":0},"gvlan_iptv2":{"FriendlyName":"WAN_GPON-IPTV_Live","Name":"gvlan_iptv2","Alias":"WAN_Virtual","NumberOfStoredMeasures":4690},"vap2g0guest0":{"FriendlyName":"2.4GHz-Guest_SSID","Name":"vap2g0guest0","Alias":"WiFi","NumberOfStoredMeasures":5858},"vap5g0guest0":{"FriendlyName":"5GHz-Guest_SSID","Name":"vap5g0guest0","Alias":"WiFi","NumberOfStoredMeasures":5854}}}`



`root@51719e1fe980:/go# ./livebox-cli -service NeMo.Intf.data -method getMIBs -params '{"traverse":"all", "flag": "statmon && !vlan"}' | jq .status.base
{
  "veip0": {
    "Name": "veip0",
    "Enable": true,
    "Status": true,
    "Flags": "netdev gpon physical netdev-monitor wan statmon enabled netdev-bound netdev-up up",
    "ULIntf": {
      "gvlan_data": {
        "Name": "gvlan_data"
      },
      "gvlan_multi": {
        "Name": "gvlan_multi"
      },
      "gvlan_voip": {
        "Name": "gvlan_voip"
      },
      "gvlan_iptv1": {
        "Name": "gvlan_iptv1"
      },
      "gvlan_iptv2": {
        "Name": "gvlan_iptv2"
      }
    },
    "LLIntf": {}
  },
  "ETH0": {
    "Name": "ETH0",
    "Enable": true,
    "Status": true,
    "Flags": "enabled netdev eth bcmeth physical netdev-monitor statmon netdev-bound netdev-up inbridge up",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {}
  },
  "ETH1": {
    "Name": "ETH1",
    "Enable": true,
    "Status": false,
    "Flags": "enabled netdev eth bcmeth physical netdev-monitor statmon netdev-bound netdev-up inbridge",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {}
  },
  "ETH2": {
    "Name": "ETH2",
    "Enable": true,
    "Status": false,
    "Flags": "enabled netdev eth bcmeth physical netdev-monitor statmon netdev-bound netdev-up inbridge",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {}
  },
  "ETH3": {
    "Name": "ETH3",
    "Enable": true,
    "Status": true,
    "Flags": "enabled netdev eth bcmeth physical netdev-monitor statmon netdev-bound netdev-up inbridge up",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {}
  },
  "ETH4": {
    "Name": "ETH4",
    "Enable": true,
    "Status": true,
    "Flags": "enabled netdev eth bcmeth physical netdev-monitor statmon netdev-bound netdev-up inbridge up",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {}
  },
  "vap2g0priv0": {
    "Name": "vap2g0priv0",
    "Enable": true,
    "Status": true,
    "Flags": "wlanvap penable netdev statmon wlan24 primary wlanvap-bound wlansta netdev-bound inbridge enabled netdev-up up",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {
      "rad2g0": {
        "Name": "rad2g0"
      }
    }
  },
  "vap2g0priv1": {
    "Name": "vap2g0priv1",
    "Enable": false,
    "Status": false,
    "Flags": "wlanvap penable netdev statmon wlan24 secondary wlanvap-bound wlansta netdev-bound inbridge netdev-up",
    "ULIntf": {
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {
      "rad2g0": {
        "Name": "rad2g0"
      }
    }
  },
  "vap5g0priv0": {
    "Name": "vap5g0priv0",
    "Enable": true,
    "Status": true,
    "Flags": "wlanvap penable netdev statmon wlan5g primary wlanvap-bound wlansta netdev-bound inbridge enabled netdev-up up",
    "ULIntf": {
      "wds5g0priv0_0": {
        "Name": "wds5g0priv0_0"
      },
      "wds5g0priv0_1": {
        "Name": "wds5g0priv0_1"
      },
      "wds5g0priv0_2": {
        "Name": "wds5g0priv0_2"
      },
      "wds5g0priv0_3": {
        "Name": "wds5g0priv0_3"
      },
      "wds5g0priv0_4": {
        "Name": "wds5g0priv0_4"
      },
      "wds5g0priv0_5": {
        "Name": "wds5g0priv0_5"
      },
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {
      "rad5g0": {
        "Name": "rad5g0"
      }
    }
  },
  "vap5g0priv1": {
    "Name": "vap5g0priv1",
    "Enable": false,
    "Status": false,
    "Flags": "wlanvap penable netdev statmon wlan5g secondary wlanvap-bound wlansta netdev-bound inbridge netdev-up",
    "ULIntf": {
      "wds5g0priv1_0": {
        "Name": "wds5g0priv1_0"
      },
      "wds5g0priv1_1": {
        "Name": "wds5g0priv1_1"
      },
      "wds5g0priv1_2": {
        "Name": "wds5g0priv1_2"
      },
      "wds5g0priv1_3": {
        "Name": "wds5g0priv1_3"
      },
      "wds5g0priv1_4": {
        "Name": "wds5g0priv1_4"
      },
      "wds5g0priv1_5": {
        "Name": "wds5g0priv1_5"
      },
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {
      "rad5g0": {
        "Name": "rad5g0"
      }
    }
  },
  "vap6g0priv0": {
    "Name": "vap6g0priv0",
    "Enable": true,
    "Status": true,
    "Flags": "wlanvap penable netdev statmon wlan6g primary wlanvap-bound wlansta enabled netdev-bound inbridge netdev-up up",
    "ULIntf": {
      "wds6g0priv0_0": {
        "Name": "wds6g0priv0_0"
      },
      "wds6g0priv0_1": {
        "Name": "wds6g0priv0_1"
      },
      "wds6g0priv0_2": {
        "Name": "wds6g0priv0_2"
      },
      "wds6g0priv0_3": {
        "Name": "wds6g0priv0_3"
      },
      "wds6g0priv0_4": {
        "Name": "wds6g0priv0_4"
      },
      "wds6g0priv0_5": {
        "Name": "wds6g0priv0_5"
      },
      "bridge": {
        "Name": "bridge"
      }
    },
    "LLIntf": {
      "rad6g0": {
        "Name": "rad6g0"
      }
    }
  },
  "vap2g0guest0": {
    "Name": "vap2g0guest0",
    "Enable": true,
    "Status": true,
    "Flags": "wlanvap penable netdev ipv4 statmon wlanvap-bound wlansta netdev-bound enabled inbridge netdev-up up",
    "ULIntf": {
      "brguest": {
        "Name": "brguest"
      }
    },
    "LLIntf": {
      "rad2g0": {
        "Name": "rad2g0"
      }
    }
  },
  "vap5g0guest0": {
    "Name": "vap5g0guest0",
    "Enable": true,
    "Status": true,
    "Flags": "wlanvap penable netdev ipv4 statmon wlanvap-bound wlansta netdev-bound netdev-up enabled inbridge up",
    "ULIntf": {
      "brguest": {
        "Name": "brguest"
      }
    },
    "LLIntf": {
      "rad5g0": {
        "Name": "rad5g0"
      }
    }
  }
}`

**Comment by Tomy2e** [comment]
Merci, mes doutes se sont confirmés. J'ai fait une modif au niveau de la découverte des interfaces, peux-tu réessayer pour voir si ça résout le problème ?

L'image Docker de test est `ghcr.io/tomy2e/livebox-exporter:dev-fix-discovery`, ou sinon il y a des binaires dispo dans les Artifacts ici: https://github.com/Tomy2e/livebox-exporter/actions/runs/10322853440

**Comment by ManuDuSud** [comment]
Plus de warning !

Je recherche plus tard  si je trouve des devices "HomeLan".

**Comment by ManuDuSud** [comment]
> Plus de warning !
> 
> Je recherche plus tard si je trouve des devices "HomeLan".

Plus de warning mais plus de livebox_wan_(tx|rx)_mbits non plus.

**Comment by Tomy2e** [comment]
> > Plus de warning !
> > Je recherche plus tard si je trouve des devices "HomeLan".
> 
> Plus de warning mais plus de livebox_wan_(tx|rx)_mbits non plus.

Pourtant je n'y ai pas touché, le flag `-experimental=livebox_interface_homelan,livebox_interface_netdev,livebox_wan` est-il bien présent ? Dans les logs il y a bien `INFO: enabled experimental metrics: livebox_wan` au démarrage ?

**Comment by ManuDuSud** [comment]
Effectivement j'ai utilisé ton image de debug mais  surcharger l'entrypoint.

Maintenant j'ai ca:

livebox-exporter-2    | 2024/08/12 11:17:24 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats
livebox-exporter-2    | 2024/08/12 11:17:30 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats
livebox-exporter-2    | 2024/08/12 11:17:35 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats
livebox-exporter-2    | 2024/08/12 11:17:41 WARN: polling failed: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats

**Comment by Tomy2e** [comment]
Ah par contre là je ne vois pas du tout où ça bloque, possible de réessayer avec cette image Docker: `ghcr.io/tomy2e/livebox-exporter:dev-fix-discovery-2` ? J'ai ajouté plus d'info aux messages d'erreur

**Comment by ManuDuSud** [comment]
Attaching to livebox-exporter-2
livebox-exporter-2    | 2024/08/12 12:31:59 INFO: enabled experimental metrics: livebox_interface_homelan
livebox-exporter-2    | 2024/08/12 12:31:59 WARN: The livebox_interface_netdev experimental metrics require a lower polling frequency, setting polling frequency to 5 seconds
livebox-exporter-2    | 2024/08/12 12:31:59 INFO: enabled experimental metrics: livebox_interface_netdev
livebox-exporter-2    | 2024/08/12 12:31:59 INFO: enabled experimental metrics: livebox_wan
livebox-exporter-2    | 2024/08/12 12:31:59 Listening on :8080
livebox-exporter-2    | 2024/08/12 12:31:59 WARN: polling failed: InterfaceNetDevMbits: failed to get stats for interface: vap6g0priv0: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats
livebox-exporter-2    | 2024/08/12 12:32:04 WARN: polling failed: InterfaceNetDevMbits: failed to get stats for interface: vap6g0priv0: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats

**Comment by Tomy2e** [comment]
Ok merci, je vois, normalement pour le problème initial ça devrait être bon.

On dirait un autre bug isolé au niveau de `livebox_interface_netdev`.

Je suis en train de chercher une solution, on est d'accord, si tu lances cette commande tu as le même message d'erreur ?

```console
livebox-cli -service NeMo.Intf.vap6g0priv0 -method getNetDevStats
```

Est-ce que avec ça c'est mieux ?

```console
livebox-cli -service NeMo.Intf.vap6g0priv0 -method getSSIDStats
```

**Comment by ManuDuSud** [comment]
**./livebox-cli-linux-amd64 -service NeMo.Intf.vap6g0priv0 -method getNetDevStats**
2024/08/12 16:54:51 request failed: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.19.Stats

**./livebox-cli-linux-amd64 -service NeMo.Intf.vap6g0priv0 -method getSSIDStats**
{"status":{"BytesSent":0,"BytesReceived":0,"PacketsSent":0,"PacketsReceived":0,"ErrorsSent":0,"RetransCount":0,"ErrorsReceived":0,"DiscardPacketsSent":0,"DiscardPacketsReceived":0,"UnicastPacketsSent":0,"UnicastPacketsReceived":0,"MulticastPacketsSent":0,"MulticastPacketsReceived":0,"BroadcastPacketsSent":0,"BroadcastPacketsReceived":0,"UnknownProtoPacketsReceived":0,"FailedRetransCount":0,"RetryCount":0,"MultipleRetryCount":0,"WmmPacketsSent":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmPacketsReceived":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmFailedSent":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmFailedReceived":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmBytesSent":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmFailedbytesSent":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmBytesReceived":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0},"WmmFailedBytesReceived":{"AC_BE":0,"AC_BK":0,"AC_VO":0,"AC_VI":0}}}

**Comment by Tomy2e** [comment]
J'ai modifié l'exporter pour qu'il utilise `getSSIDStats` sur les interfaces WLAN: `ghcr.io/tomy2e/livebox-exporter:dev-fix-discovery-3`

Est-ce que ça corrige l'erreur ?

**Comment by ManuDuSud** [comment]
Et voici :

livebox-exporter-2    | 2024/08/13 12:20:21 WARN: polling failed: InterfaceNetDevMbits: failed to get stats for interface: vap6g0priv0: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.42.Stats
livebox-exporter-2    | 2024/08/13 12:20:27 WARN: polling failed: InterfaceNetDevMbits: failed to get stats for interface: vap6g0priv0: Error: 196618, Description: Object or parameter not found, Info: NetDev.Link.42.Stats

**Comment by Tomy2e** [comment]
Ah oui c'est ma faute, j'avais oublié d'intégrer le correctif dans l'image précédente, est-ce que c'est mieux avec celle-ci: `ghcr.io/tomy2e/livebox-exporter:dev-fix-discovery-4` ?

**Comment by ManuDuSud** [comment]
Pas de soucis.
Plus de logs !

je vois des valeurs sur interface_homelan ...etc

**Comment by Tomy2e** [comment]
Parfait, j'ai mis en ligne la version [v0.5.0](https://github.com/Tomy2e/livebox-exporter/releases/tag/v0.5.0) avec les correctifs pour la Livebox 7.
