### ISSUE TITLE
ARM64 - Failed to discover Livebox interfaces: no interfaces found 

### ISSUE THREAD

**Issue by romainnicolas125** [Tomy2e/livebox-exporter#18]
Hello,

Je me suis permis de tester ton package ARM64 v0.4.0 sur un RPi 

Malheureusement, quand j'exécute le binaire, j'obtiens l'erreur ci-dessous :
![image](https://github.com/user-attachments/assets/096b21bc-cec1-4e31-ba4d-7287e9db78d6)

Suivant les intructions, j'ai bien rajouté au préalable la variable d'env ADMIN_PASSWORD.

dans le doutes, j'ai aussi rajouté la variable d'env LIVEBOX_ADDRESS
mais pas de chance toujours la même erreur

ci-dessous un petit echo de chaque variable
![image](https://github.com/user-attachments/assets/e6be8ef6-3097-4196-ade8-b133f519405b)

Test effectué avec Livebox 3, et oui dsl la fibre est pas encore arrivé jusqu'a moi :)

en regardant sur un autre ticket, jai récup le livebox-cli et lancé la commande suivante pour voir si ça répond et pas d'erreur et quelques infos remontées

> pi@hass:~/Livebox $ ./livebox-cli-linux-arm64 -service HomeLan.Interface -method get
{"status":{"wl0":{"FriendlyName":"802.11-2.4GHz","Name":"wl0","NumberOfStoredMeasures":2880},"wl1":{"FriendlyName":"802.11-5GHz","Name":"wl1","NumberOfStoredMeasures":2880},"wl2":{"FriendlyName":"Orange","Name":"wl2","NumberOfStoredMeasures":0},"wl3":{"FriendlyName":"Orange_autoconnect","Name":"wl3","NumberOfStoredMeasures":0},"swport1":{"FriendlyName":"Ethernet1","Name":"swport1","NumberOfStoredMeasures":2880},"swport2":{"FriendlyName":"Ethernet2","Name":"swport2","NumberOfStoredMeasures":2880},"swport3":{"FriendlyName":"Ethernet3","Name":"swport3","NumberOfStoredMeasures":508},"swport4":{"FriendlyName":"Ethernet4","Name":"swport4","NumberOfStoredMeasures":2880},"wan":{"FriendlyName":"ADSL","Name":"dsl0","NumberOfStoredMeasures":2880}}}

> pi@hass:~/Livebox $ ./livebox-cli-linux-arm64 -service NeMo.Intf.data -method getMIBs -params '{"traverse":"all", "flag": "statmon && !vlan"}'
{"status":{"base":{},"6rd":{},"alias":{},"atm":{},"bridge":{},"copy":{},"dhcp-api":{},"dhcp":{},"dhcpv6":{},"dhcpv6impl":{},"dop-slave":{},"dsl":{},"dslbonding":{},"dslite":{},"dslline":{},"eth":{},"gre":{},"nat":{},"netdev-api":{},"netdev":{},"penable":{},"ppp":{},"ptm":{},"ra-api":{},"ra":{},"switch":{},"vlan":{},"wlanconfig":{},"wlanendpoint":{},"wlanradio":{},"wlanvap":{}}}

**Comment by Tomy2e** [comment]
Bonjour, merci pour toutes ces infos, je ne sais pas si je vais être en mesure de supporter la Livebox 3.

Au vu du résultat de la commande, `./livebox-cli-linux-arm64 -service NeMo.Intf.data -method getMIBs -params '{"traverse":"all", "flag": "statmon && !vlan"}'`, l'erreur est "normale", on ne voit aucune interface dans la liste.

Avant que je regarde plus en profondeur, est-ce possible d'essayer avec la version [v0.3.1](https://github.com/Tomy2e/livebox-exporter/releases/tag/v0.3.1) que je viens de mettre en ligne et me dire si l'exporter fonctionne correctement (les metrics listées dans le [README](https://github.com/Tomy2e/livebox-exporter/tree/release-v0.3?tab=readme-ov-file#metrics) remontent correctement, à l'exception des metrics expérimentales). Sur cette version, l'exporter n'a pas besoin de lister les interfaces au démarrage, il ne devrait donc pas y avoir cette erreur.

**Comment by romainnicolas125** [comment]
Bonjour, 

Merci pour ton retour,

Le programme se lance mais des "WARN" apparaissent au moment de polling.

> pi@hass:~/Livebox $ ./livebox-exporter-linux-arm64.1 -listen :8888
2024/08/17 11:29:28 Listening on :8888
2024/08/17 11:29:28 **WARN**: polling failed: failed to get interfaces: json: cannot unmarshal array into Go struct field .status of type struct { Traffic []struct { Timestamp int "json:\"Timestamp\""; RxCounter int "json:\"Rx_Counter\""; TxCounter int "json:\"Tx_Counter\"" } "json:\"Traffic\"" }
2024/08/17 11:29:58 **WARN**: polling failed: failed to get interfaces: json: cannot unmarshal array into Go struct field .status of type struct { Traffic []struct { Timestamp int "json:\"Timestamp\""; RxCounter int "json:\"Rx_Counter\""; TxCounter int "json:\"Tx_Counter\"" } "json:\"Traffic\"" }

Le port est bien en écoute, mais une erreur 404 page  not found remonte via curl

> pi@hass:~ $ curl http://localhost:8888
404 page not found
pi@hass:~ $ sudo netstat -nutelap | grep 8888
tcp6       0      0 :::8888                 :::*                    LISTEN      1000       26006432   1487869/./livebox-e
tcp6       0      0 ::1:39244               ::1:8888                TIME_WAIT   0          0          -
pi@hass:~ $

**Comment by romainnicolas125** [comment]
Hello,

Pas besoin de passer plus de temps sur ce pb.

je vais basculer sur Livebox 5, la fiber arrive chez moi, d'ici 1 mois et je prendrais le temps de teste le livebox exporter sur cette nouvelle box.

Merci en tout cas pour tes retours et le temps passsé.

on peut clore ce ticket

**Comment by Tomy2e** [comment]
Hello, c'est une bonne nouvelle, je ferme le ticket alors.

Au vu des logs fournis, je pense que ça risque de demander pas mal de travail pour supporter la Livebox 3. Et vu que je n'ai pas le matériel à disposition ça ne facilite pas les choses.

Si quelqu'un est motivé pour le faire à l'avenir, je reste ouvert aux contributions
