### ISSUE TITLE
Prometheus configuration exemple

### ISSUE THREAD

**Issue by mabed-fr** [Tomy2e/livebox-exporter#2]
Hello

Can you add exemple of configuration to use this exporter with existing prometheus ?

Mabed

**Comment by Tomy2e** [comment]
Hi,

The [README.md](https://github.com/Tomy2e/livebox-exporter/blob/main/README.md) already describes how to run and configure the exporter.

For the Prometheus configuration I think it's better to refer to the [Prometheus documentation](https://prometheus.io/docs/introduction/overview/) directly as it depends on how it's deployed and configured.

If your Prometheus doesn't use service discovery, you can just add a static target that points to the exporter as described [here in the Prometheus documentation](https://prometheus.io/docs/prometheus/latest/getting_started/#configure-prometheus-to-monitor-the-sample-targets).

I'm closing this issue but feel free to reopen it if you think there are some missing information.
