### ISSUE TITLE
Add variable for a different IP address

### ISSUE THREAD

**Issue by Mika64** [Tomy2e/livebox-exporter#6]
Hello,

My lb4 have a different IP address than 192.168.1.1.

Can we have an environment variable to set livebox's ip address (like: LB_ADDRESS) ?

Regards,

**Comment by Tomy2e** [comment]
Hello,

Yes I can add support for using a different Livebox address.

This will first require some changes on [livebox-api-client](https://github.com/Tomy2e/livebox-api-client).

**Comment by Tomy2e** [comment]
I just released the v0.3.0 version of the exporter which includes the `LIVEBOX_ADDRESS` environment variable. It's set to 
`http://192.168.1.1/` by default. Full documentation is [here](https://github.com/Tomy2e/livebox-exporter#usage).
I never tried the exporter on a lb4, do not hesitate to let me know how it goes.
